package enums

const (
	USER_PERMISSION_TYPE_NORMAL = "NORMAL"

	USER_VALIDATION_FIELD_EMAIL    = "EMAIL"
	USER_VALIDATION_FIELD_NAME     = "NAME"
	USER_VALIDATION_FIELD_PASSWORD = "PASSWORD"
	USER_VALIDATION_FIELD_TOKEN    = "TOKEN"
	USER_VALIDATION_FIELD_FORM     = "FORM"

	USER_PASSWORD_MIN_SIZE = 8
)
