// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.deleteTransactionByIDStmt, err = db.PrepareContext(ctx, deleteTransactionByID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTransactionByID: %w", err)
	}
	if q.insertTransactionStmt, err = db.PrepareContext(ctx, insertTransaction); err != nil {
		return nil, fmt.Errorf("error preparing query InsertTransaction: %w", err)
	}
	if q.insertUserStmt, err = db.PrepareContext(ctx, insertUser); err != nil {
		return nil, fmt.Errorf("error preparing query InsertUser: %w", err)
	}
	if q.selectTransactionByIDStmt, err = db.PrepareContext(ctx, selectTransactionByID); err != nil {
		return nil, fmt.Errorf("error preparing query SelectTransactionByID: %w", err)
	}
	if q.selectTransactionsStmt, err = db.PrepareContext(ctx, selectTransactions); err != nil {
		return nil, fmt.Errorf("error preparing query SelectTransactions: %w", err)
	}
	if q.selectTransactionsTotalStmt, err = db.PrepareContext(ctx, selectTransactionsTotal); err != nil {
		return nil, fmt.Errorf("error preparing query SelectTransactionsTotal: %w", err)
	}
	if q.selectUserForLoginStmt, err = db.PrepareContext(ctx, selectUserForLogin); err != nil {
		return nil, fmt.Errorf("error preparing query SelectUserForLogin: %w", err)
	}
	if q.selectUserIDByEmailStmt, err = db.PrepareContext(ctx, selectUserIDByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query SelectUserIDByEmail: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.deleteTransactionByIDStmt != nil {
		if cerr := q.deleteTransactionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTransactionByIDStmt: %w", cerr)
		}
	}
	if q.insertTransactionStmt != nil {
		if cerr := q.insertTransactionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertTransactionStmt: %w", cerr)
		}
	}
	if q.insertUserStmt != nil {
		if cerr := q.insertUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertUserStmt: %w", cerr)
		}
	}
	if q.selectTransactionByIDStmt != nil {
		if cerr := q.selectTransactionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing selectTransactionByIDStmt: %w", cerr)
		}
	}
	if q.selectTransactionsStmt != nil {
		if cerr := q.selectTransactionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing selectTransactionsStmt: %w", cerr)
		}
	}
	if q.selectTransactionsTotalStmt != nil {
		if cerr := q.selectTransactionsTotalStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing selectTransactionsTotalStmt: %w", cerr)
		}
	}
	if q.selectUserForLoginStmt != nil {
		if cerr := q.selectUserForLoginStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing selectUserForLoginStmt: %w", cerr)
		}
	}
	if q.selectUserIDByEmailStmt != nil {
		if cerr := q.selectUserIDByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing selectUserIDByEmailStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                          DBTX
	tx                          *sql.Tx
	deleteTransactionByIDStmt   *sql.Stmt
	insertTransactionStmt       *sql.Stmt
	insertUserStmt              *sql.Stmt
	selectTransactionByIDStmt   *sql.Stmt
	selectTransactionsStmt      *sql.Stmt
	selectTransactionsTotalStmt *sql.Stmt
	selectUserForLoginStmt      *sql.Stmt
	selectUserIDByEmailStmt     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                          tx,
		tx:                          tx,
		deleteTransactionByIDStmt:   q.deleteTransactionByIDStmt,
		insertTransactionStmt:       q.insertTransactionStmt,
		insertUserStmt:              q.insertUserStmt,
		selectTransactionByIDStmt:   q.selectTransactionByIDStmt,
		selectTransactionsStmt:      q.selectTransactionsStmt,
		selectTransactionsTotalStmt: q.selectTransactionsTotalStmt,
		selectUserForLoginStmt:      q.selectUserForLoginStmt,
		selectUserIDByEmailStmt:     q.selectUserIDByEmailStmt,
	}
}
